yamlname: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]





    


      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov on insecure Terraform files
        run: |
          checkov -d terraform/insecure --framework terraform
        continue-on-error: true

      - name: Run Checkov on secure Terraform files
        run: |
          checkov -d terraform/secure --framework terraform
