name: Security-scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkov-scan:
    name: Checkov Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov on insecure Terraform files
        run: |
          checkov -d terraform/insecure --framework terraform
        continue-on-error: true

      - name: Run Checkov on secure Terraform files
        run: |
          checkov -d terraform/secure --framework terraform
